#!/usr/bin/bash

#   This template identifies the functions required to supported by each OS

#function create_vm() {
#    #    This function can be used to over rid the standard function in quickget
#    #    if you distribution requires something special. Windows and Mac are examples..
#}

# This function returns an associative array with keys "url", "iso", and "hash"
# Change this function for your distro
function get_distro_info() {
    declare -A distro_info
    distro_info['url']="https://repo.almalinux.org/almalinux/${RELEASE}/isos/x86_64"
    distro_info['iso']="AlmaLinux-${RELEASE}-latest-x86_64-${EDITION}.iso"
    distro_info['hash']="$(wget -q -O- "${distro_info['url']}"/CHECKSUM | grep \("${distro_info['iso']}"\) | cut -d' ' -f4)"

    echo "${distro_info[@]@k}"
}

#function get_file() {
#    #    This function can be used to over rid the standard function in quickget
#    #    if you distribution requires something special. Windows and Mac are examples..
#}

# This funciton returns supported OS releases for the OS
# Change this function for your distro
function releases() {
    echo latest
}

# This function returns an associative array with releases as the key
# and a "!" separated string of valid editions for the specific release.
# While quite often editions are the same for all releases it is not always
# the case.
# Editions have different meanings for different OS's
# Change this function for your distro
function editions() {
    declare -A editions
    local release

    for release in $(releases); do
        editions[${release}]="boot!minimal!dvd"
    done

    echo "${editions[@]@k}"
}

# Change this function for your distro
# Returning 0 means editions are required and 1 not required
function editions_required() {
    return 0
}

# This function returns an expanded OS name for pretty printing
# Change this function for your distro
function pretty_name() {
    echo "Alma Linux"
}

# This function returns the OS's home page URL
# Change this function for your distro
function homepage() {
    echo "https://almalinux.org/"
}

# This function creates the vm_config file and can be used to
# replace the default one in the quickget
# Change this function for your distro
function make_vm_config() {
    default_vm_config

    # Override any default settings
    sed -i 's/guest_os=.*/guest_os="batocera"/' "${VM_PATH}".conf
    sed -i 's/^disk_size=.*/disk_size=\"80G\"/' "${VM_PATH}".conf
    sed -i 's/iso=/img=/' "${VM_PATH}".conf

    # Add any additional lines
    # {
    #     printf "fixed_iso=\"%s\"\n"   ${fixed_iso}
    #
    # } >> "${VM_PATH}.conf"
}
